### ISSUE TITLE
Host resoruces at another repository

### ISSUE THREAD

**Issue by m1kit** [m1kit/yalm-python#1]
Host license-matching resources at [another repository](https://github.com/m1kit/license-matcher-resources/tree/dist). The repository may include the following:

- [x] The list of licences (See https://github.com/spdx/spdx_python_licensematching/issues/12)
- [x] License templates
- [x] Transpiled license templates (regex)
- [x] Transpiled license templates (words)
- [x] Statistics on the most commonly used licenses
  - Needed to prioritize licenses that will be used frequently
- [x] Test files

This information will need to be regenerated as the data like [license-list-data](https://github.com/spdx/license-list-data) is updated. Currently this is done with GitHub Actions (updated once a week).

This kind of information is needed when implementing the license matcher in languages other than python, so it would be useful to have it in a separate repository. Each license matcher can add resources as a git submodule.

**Comment by m1kit** [comment]
If we take this policy, we need to generate tests automatically. Maybe I can generate tests from templates (using an `original` attribute in `var` tag).

**Comment by goneall** [comment]
Could this data be added as subdirectories in the license-list-data repo?

**Comment by m1kit** [comment]
Of course it is possible. In that case, I will implement the generator in java as a part of Spdx-Java-Library.

**Comment by m1kit** [comment]
One more question: do you agree with adding a new structured format template like this? I prefer JSON, but also XML is acceptable.

```json
[{
		"type": "optional",
		"content": [{
			"type": "plain",
			"text": "MIT License"
		}]
	}, {
		"type": "var",
		"name": "copyright",
		"original": "Copyright (c) <year> <copyright holders>  ",
		"pattern": ".{0,5000}"
	},
	{
		"type": "plain",
		"text": "Permission is hereby granted, free of charge, ..."
	}
]
```

**Comment by anshuldutt21** [comment]
Yes I think it is fine to structure it in this manner.

**Comment by goneall** [comment]
I like the idea of putting the template into a more parseable form like JSON and XML.

From a technical perspective, I think the structure proposed is fine.

If we want to treat this as a standard usable beyond the specific library we will need to get consensus from the broader community which will take some time and effort, but could well be worth it in terms of increased usage.  The way to start this is to add a proposal to the SPDX spec - it would be added to the [license matching guidelines appendix](https://github.com/spdx/spdx-spec/blob/development/v2.2.1/chapters/license-matching-guidelines-and-templates.md).

This does overlap with the existing template spec and the existing [License List XML schema](https://github.com/spdx/license-list-XML/blob/master/schema/ListedLicense.xsd).  This may cause some concerns in standardization.

I have thought about using the license list XML schema directly in the tools rather than using the templates.  This would provide a similar purpose, however, there are some "implied" var matches which would require additional interpretation.  The License List XML is also a schema used internally to the legal team and not standardized, so we would have to standardize it.

**Comment by goneall** [comment]
Another consideration - if we do choose JSON and we want to standardize this, do we want to create a separate set of files or do we want to add this to the existing license JSON format?

**Comment by m1kit** [comment]
The reason I prefer JSON is that it is easy to include in existing web APIs. Also, if the data format of resources can be unified into JSON, it will be easier to port to other languages.
Of course, I understand the merits of XML, so I'll leave the decision to the community, but I suspect it will take some time before we find a new format for license-list-data.
Since the deadline for GSoC is fixed, I'd like to try to generate JSON in my personal repository without consensus first.

**Comment by goneall** [comment]
@m1kit I agree with all your points above.

**Comment by m1kit** [comment]
I'm reading the code for the template generation

**Comment by goneall** [comment]
> I'm reading the code for the template generation.

@m1kit thanks for the update.  Let me know if you have any questions on this code.

**Comment by m1kit** [comment]
Hi @goneall, I have few questions about the code above.

1. Is the intended behavior that [the text node inside the list element node is simply ignored](https://github.com/spdx/LicenseListPublisher/blob/master/src/org/spdx/licensexml/LicenseXmlHelper.java#L518)? 

2. The matching guideline states `name` tag should be unique, but the generator assigns the name `bullet` for multiple tags. Why does the guideline say the name is unique?
> name: name of the field in the template.
> - This field is unique within each license template.
> - This field is required.

3. Maybe typo?
- https://github.com/spdx/LicenseListPublisher/blob/master/src/org/spdx/licensexml/LicenseXmlHelper.java#L343
  - The last char in `sb` is always `>` of `<<beginOptional>>`

**Comment by goneall** [comment]
> Is the intended behavior that the text node inside the list element node is simply ignored?

It does look like the text nodes are ignored.  I'm not sure if this is intentional or not.  It would seem we would want to insert the text between list items if they did show up - so this may be a defect.  In practice, there likely won't be very many nodes other than list items.  It would be interesting to see if any text nodes appear between list items with the current license list.

> The matching guideline states name tag should be unique, but the generator assigns the name bullet for multiple tags. Why does the guideline say the name is unique?

You are correct in that this rule is ignored by the generator.  The original reason for making the names unique was so tooling could use the name to assign semantic meaning to variable tags.  To date, no one has raised an issue with not having the names unique, but we probably should implement the spec and generate some kind of unique name.  Probably worth adding an issue to the licenseListPublisher to track.

> Maybe typo? The last char in sb is always > of <<beginOptional>>

Definitely a defect - good catch!  Likely due to copy/paste from the text section.  It looks like:

`else if (sb.length() > 0 && !Character.isWhitespace(sb.charAt(sb.length()-1))`

should be changed to:

`else if (sb.length() > "<<beginOptional>>".lenght() && !Character.isWhitespace(sb.charAt(sb.length()-("<<beginOptional>>".lenght()+1)))`

**Comment by m1kit** [comment]
I confirmed there are no non-empty text nodes under the list tag.

I created issues in the publisher repo, the first and third ones are small fixes, so I'll probably clean them up.

**Comment by m1kit** [comment]
I created [a parser for the license xml](https://github.com/m1kit/license-matcher-resources/blob/main/src/generators/spdx_xml/nodes.py), and it dumps a template in [structured format](https://github.com/m1kit/license-matcher-resources/tree/dist/template).

There are still some imperfections in the handling of spaces, and your advice and pointers to problems are welcome.

**Comment by m1kit** [comment]
Progress report: [I added static tests and dynamically generated tests](https://github.com/m1kit/license-matcher-resources/tree/dist/tests/classfier/positive).

**Comment by m1kit** [comment]
Working on [feature/externalize-resources branch](https://github.com/m1kit/yalm-python/tree/feature/externalize-resources)

**Comment by m1kit** [comment]
Now I added pre-transplied regexes.
https://github.com/m1kit/yalm-resources/tree/dist/regex
